### ISSUE TITLE
Update dbus to 0.5.1

### ISSUE THREAD

**Issue by nox** [szeged/blurz#6]
This crate is lagging behind 2 major versions of dbus, could we get a bump for it @szeged?

**Comment by nox** [comment]
Am stupid. Cc @dati91.

**Comment by dati91** [comment]
Done.
For servo, [this](https://github.com/servo/devices/blob/master/Cargo.toml#L12) repo should be updated as well.

**Comment by nox** [comment]
No it's ok, `0.2.2` is compatible with `0.2.1`.
