### ISSUE TITLE
BluetoothGATTCharacteristic::write_value dbus error

### ISSUE THREAD

**Issue by CromFr** [szeged/blurz#7]
When trying to usr BluetoothGATTCharacteristic::write_value, it returns `D-Bus error: Method "WriteValue" with signature "ay" on interface "org.bluez.GattCharacteristic1" doesn't exist (org.freedesktop.DBus.Error.UnknownMethod)`

I'm not sure if the issue is on my end or not, since I'm a rust beginner and almost never used dbus before. My supposition is that WriteValue should have a signature like `ay{sv}` since the dbus method has two parameters (see below)

When trying to connect and write values with `btgatt-client` and `write-long-value 0x0021 0 0x55 0x10 0x01 0x0d 0x0a`, it works as expected.

### DBus entry for this characteristic:
![screenshot from 2017-04-06 20-50-48](https://cloud.githubusercontent.com/assets/999188/24770601/c789c6fc-1b0a-11e7-8d10-71949fc572e8.png)

### GATT services/charac/descr: 
```
service - start: 0x001f, end: 0x002f, type: primary, uuid: a8b3fff0-4834-4051-89d0-3de95cddd318
	  charac - start: 0x0020, value: 0x0021, props: 0x0a, ext_props: 0x0000, uuid: a8b3fff1-4834-4051-89d0-3de95cddd318
		  descr - handle: 0x0022, uuid: 00002901-0000-1000-8000-00805f9b34fb
	  charac - start: 0x0023, value: 0x0024, props: 0x02, ext_props: 0x0000, uuid: a8b3fff2-4834-4051-89d0-3de95cddd318
		  descr - handle: 0x0025, uuid: 00002901-0000-1000-8000-00805f9b34fb
	  charac - start: 0x0026, value: 0x0027, props: 0x08, ext_props: 0x0000, uuid: a8b3fff3-4834-4051-89d0-3de95cddd318
		  descr - handle: 0x0028, uuid: 00002901-0000-1000-8000-00805f9b34fb
	  charac - start: 0x0029, value: 0x002a, props: 0x10, ext_props: 0x0000, uuid: a8b3fff4-4834-4051-89d0-3de95cddd318
		  descr - handle: 0x002b, uuid: 00002902-0000-1000-8000-00805f9b34fb
		  descr - handle: 0x002c, uuid: 00002901-0000-1000-8000-00805f9b34fb
	  charac - start: 0x002d, value: 0x002e, props: 0x02, ext_props: 0x0000, uuid: a8b3fff5-4834-4051-89d0-3de95cddd318
		  descr - handle: 0x002f, uuid: 00002901-0000-1000-8000-00805f9b34fb
```

### Full code
https://gist.github.com/CromFr/7938362577028de485b8ca6d7029c6f7

### Config:
- ArchLinux 06/04/2017
- bluetoothd version 5.44. Started with `bluetoothd -E --noplugin=sap`

**Comment by dati91** [comment]
Hi!

The problem seems to be that 5.44 is too new.
The last supported version was 5.39.
You can see the difference between the two signature here: [5.39](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt?h=5.39&id=969cc06e08d613f58b113bbc60c2ba25dfda3b25#n76) vs [5.44](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n79)

Feel free to send a pull request with an update. If not i will try to make time for this.
